// <auto-generated />
using System;
using Controle_Estoque_Basico.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Controle_Estoque_Basico.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Controle_Estoque_Basico.Models.Categoria", b =>
                {
                    b.Property<int>("CAT_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("CAT_ISDELETED")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CAT_NOME")
                        .IsRequired()
                        .HasColumnType("varchar(30) CHARACTER SET utf8mb4")
                        .HasMaxLength(30);

                    b.HasKey("CAT_ID");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("Controle_Estoque_Basico.Models.Produto", b =>
                {
                    b.Property<int>("PRO_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("PRO_DATAENTRADA")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PRO_DESCRICAO")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("PRO_IDCATEGORIA")
                        .HasColumnType("int");

                    b.Property<bool>("PRO_ISDELETED")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PRO_NOME")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<decimal>("PRO_QUANTIDADE")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<bool>("PRO_STATUS")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("PRO_VALIDADE")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PRO_ID");

                    b.HasIndex("PRO_IDCATEGORIA");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("Controle_Estoque_Basico.Models.Produto", b =>
                {
                    b.HasOne("Controle_Estoque_Basico.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("PRO_IDCATEGORIA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
